### PR TITLE
React Bookstore App (feature/redux in react components)

### PR DESCRIPTION
**Pull request by lucy-sees**
### In this part of my project I did the following,

- [x] Understood the concept of state management.
- [x] Used store, actions and reducers in React.
- [x] Connected React and Redux.
- [x] Wrapped my `<App>` with the `<Provider>` component from `react-redux`.
- [x] Passed my configured store into the '<Provider>'.
- [x] Created `initialState` variable for your `booksSlice`.

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @lucy-sees, please fix the Stylelint errors and remove the live demo section from your readme 👍🏿

**Comment by prolajumokeoni** [comment]
Hi @lucy-sees, please remove the live demo section in your readme for now, till you deploy the app 👍🏿

**Comment by lucy-sees** [comment]
Hi @prolajumokeoni , I have made the requested changes.

**Review by prolajumokeoni — CHANGES_REQUESTED** [review]
Hi @lucy-sees 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
 - Implemented correctly the functions to remove and add book  ✅ 
-  Defined an initial state slice that contains books and added to booksSlice 🚀 




## Required Changes ♻️

- [ ] Kindly fix the link to your issues page in your readme it is currently showing a 404 error page 👍🏿 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ademibowale — APPROVED** [review]
Hi @lucy-sees  


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 
- No linters errors ✔️
- Dispatch actions using useDispatch✔️
- Pass your configured store into the <Provider>`✔️
- Uses `configureStore` to create a reducer✔️
- Create an initialState variable for your booksSlice,✔️
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good use of Github flow ✔️






- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
